---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tilbakemeldinger
  namespace: navno
  labels:
    team: navno
spec:
  image: {{image}}
  port: 9001
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  liveness:
    path: /person/kontakt-oss/tilbakemeldinger/internal/isAlive
    initialDelay: 10
  readiness:
    path: /person/kontakt-oss/tilbakemeldinger/internal/isReady
    initialDelay: 10
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  azure:
    application:
      enabled: true
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level3
  accessPolicy:
    outbound:
      rules:
        - application: tilbakemeldingsmottak-api
          namespace: teamserviceklage
        - application: nav-dekoratoren
      external:
        - host: {{norg2Host}}
  replicas:
  {{#with replicas}}
    min: {{min}}
    max: {{max}}
  {{/with}}
  resources:
  {{#with resources}}
    requests:
      cpu: {{requests.cpu}}
      memory: {{requests.memory}}
    limits:
      memory: {{limits.memory}}
  {{/with}}
