---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tilbakemeldinger
  namespace: {{namespace}}
  labels:
    team: personbruker
spec:
  image: {{image}}:{{version}}
  team: personbruker
  port: 8080
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  liveness:
    path: /person/kontakt-oss/tilbakemeldinger/internal/isAlive
    initialDelay: 10
  readiness:
    path: /person/kontakt-oss/tilbakemeldinger/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  webproxy: true
  azure:
    application:
      enabled: true
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: tilbakemeldinger-api
          namespace: personbruker
          cluster: prod-fss
      external:
        - host: nav.no
        - host: tilbakemeldingsmottak-gcp.intern.nav.no
        - host: norg2.prod-fss-pub.nais.io
  leaderElection: true
  env:
    - name: ENV
      value: prod
    - name: API_URL
      value: https://tilbakemeldingsmottak-gcp.intern.nav.no/rest
    - name: NORG2_URL
      value: https://norg2.prod-fss-pub.nais.io
    - name: API_AUDIENCE
      value: prod-gcp:teamserviceklage:tilbakemeldingsmottak-api

  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 128Mi
