import { buildHtmlTemplate, getTemplateWithDecorator } from './templateBuilder';
import { ViteDevServer } from 'vite';
// @ts-ignore (this file is generated by vite build)
import { render } from '../../_ssr-dist/main-server';
import { Locale, defaultLocale, translate } from '../../../../common/locale';
import { getLastSegmentFromUrl, checkIfPage } from '../../utils/utils';
import { HelmetServerState } from 'react-helmet-async';

export type HtmlRenderer = (url: string) => Promise<string>;

function getLocaleFromUrl(url: string) {
    const regex = /\/kontakt-oss\/([a-z]{2})\//;
    const match = url.match(regex);

    if (match && match[1]) return match[1];
    return defaultLocale;
}

const processTemplate = async (
    templateHtml: string,
    appHtml: string,
    url: string,
    helmet?: HelmetServerState //TODO type
) => {
    const title = helmet?.title.toString();
    const description = helmet?.meta.toString();

    console.log('helmet', helmet?.meta.toString());

    return templateHtml
        .replace('<!--ssr-app-html-->', appHtml)
        .replace('%%TITLE%%', `${title} - www.nav.no`)
        .replace('%%DESCRIPTION%%', description ? description : 'nodescription')
        .replace('CANONICAL_TO_BE_REPLACED', `https://www.nav.no${url}`);
};

export const prodRender: HtmlRenderer = async (url) => {
    const template = await getTemplateWithDecorator(url);

    try {
        const { html, helmet } = render(url);
        return processTemplate(template, html, url, helmet); //TODO fjern url?
    } catch (e) {
        console.error(`Rendering failed ${e}}`);
        return processTemplate(template, '', url);
    }
};

const devErrorHtml = (e: Error) => {
    return `
        <div style='max-width: 1344px;width: 100%;margin: 1rem auto'>
            <span>Server rendering error: ${e}</span>
            <div style='font-size: 0.75rem; margin-top: 1rem'>
                <code>${e.stack}</code>
            </div>
        </div>`;
};

export const devRender =
    (vite: ViteDevServer): HtmlRenderer =>
    async (url) => {
        const template = await buildHtmlTemplate();
        const html = await vite.transformIndexHtml(url, template);

        try {
            const { render } = await vite.ssrLoadModule('/src/main-server.tsx');
            const appHtml = render(url);
            return processTemplate(html, appHtml, url);
        } catch (e: any) {
            vite.ssrFixStacktrace(e);
            console.error(`Dev render error: ${e} \n ${e.stack}`);
            return processTemplate(html, devErrorHtml(e), url);
        }
    };
