name: Build and deploy to nais
on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      imageSuffix:
        required: true
        type: string
    secrets:
      READER_TOKEN:
        required: true
      NAIS_WORKLOAD_IDENTITY_PROVIDER:
        required: true
      NAIS_DEPLOY_APIKEY:
        required: true

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    environment: ${{ inputs.env }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'
      - name: Set app environmment
        run: |
          cat > .env <<EOF
          ENV=${{ inputs.env }}
          VITE_APP_BASEPATH=/person/kontakt-oss
          APP_PORT=9001
          API_URL=http://tilbakemeldingsmottak-api.teamserviceklage
          NORG2_URL=https://norg2.${{ inputs.env }}-fss-pub.nais.io
          CDN_BASE=https://cdn.nav.no/personbruker/tilbakemeldinger/${{ inputs.env }}
          EOF
      - name: Define client-side environment
        run: |
          echo "REACT_APP_ENV=dev" >> $GITHUB_ENV
          echo "REACT_APP_HOST=https://www.intern.dev.nav.no" >> $GITHUB_ENV
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Build application
        run: npm run build
      - name: Upload static files to CDN
        uses: navikt/frontend/actions/cdn-upload/v1@main
        with:
          cdn-team-name: personbruker
          source: ./server/dist/client/assets
          destination: tilbakemeldinger/${{ inputs.env }}
      - name: Build and push docker image
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: personbruker
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          image_suffix: ${{ inputs.imageSuffix }}
      - name: Deploy to nais
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: ${{ inputs.env }}-gcp
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: .nais/config.yml
          VAR: image=${{ steps.docker-push.outputs.image }}
          VARS: .nais/vars-${{ inputs.env }}.yml