name: Deploy to prod
on:
  release:
    types: [released]

jobs:
  build:
    if: github.event.release.target_commitish == 'master'
    uses: ./.github/workflows/build-and-deploy.yml
    permissions:
      contents: "read"
      id-token: "write"
    with:
      env: prod
      imageSuffix: release-${{ github.ref_name }}
      appOrigin: "https://www.nav.no"
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
