name: PR Checks
on:
  pull_request:
    branches:
      - 'main'

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
      - name: Build and deploy
        uses: ./.github/actions/build-and-deploy
        with:
          env: dev
          appOrigin: 'https://www.ansatt.dev.nav.no'
          editorialFrontpageOrigin: 'https://www.ansatt.dev.nav.no/tilbakemelding'
          skipDeploy: true
        env:
          READER_TOKEN: ${{ secrets.READER_TOKEN }}
