name: PR Checks
on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  check:
    uses: navikt/navno-ci/.github/workflows/node-build.yml@v1
    with:
      push-image: false
      env-file: |
        ENV=dev
        VITE_APP_BASEPATH=/person/kontakt-oss
        VITE_APP_ORIGIN=https://www.ansatt.dev.nav.no
        VITE_EDITORIAL_FRONTPAGE_ORIGIN=https://www.ansatt.dev.nav.no/tilbakemelding
        VITE_TELEMETRY_URL=https://telemetry.ekstern.dev.nav.no/collect
        APP_PORT=9001
        API_URL=http://tilbakemeldingsmottak-api.teamserviceklage
        NORG2_ORIGIN=https://norg2.dev-fss-pub.nais.io
        CDN_BASE=https://cdn.nav.no/navno/tilbakemeldinger/dev
    secrets: inherit
